# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-29 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('frcomment', '0002_auto_20181129_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=40),
        ),
    ]
